[package]
name = "pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.22.0"
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "macros"] }
bytes = "1.5.0"