[package]
name = "broker"
version = "0.1.0"
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttd = "0.18.0"
config = "0.13.3"
clap = "4.4.6"
tracing-subscriber = "0.3.17"